
#
# This LookML file was generated by AtScale on 2024-06-25T16:26:09.706622668Z
#
# AtScale engine version: 2024.1.0.12792
# AtScale DesignCenter version: 2024.1.0.21169
# AtScale version: 2024.1.0.6834
# Organization: default
# Project: Date Looker Test

connection: "atscale-lm"
label: "Date Looker Test"


include: "/views/Date_Looker_Test/Date_Looker_Test.view.lkml"


explore: Date_Looker_Test {
  label: "Date Looker Test"
}

