
#
# This LookML file was generated by AtScale on 2024-06-25T11:50:29.274510788Z
#
# AtScale engine version: 2024.1.0.12792
# AtScale DesignCenter version: 2024.1.0.21169
# AtScale version: 2024.1.0.6834
# Organization: default
# Project: Date_Looker_Test

connection: "atscale-lm"
label: "Date_Looker_Test"


include: "/views/Date__Looker__Test/Date__Looker__Test.view.lkml"


explore: Date_Looker_Test {
  label: "Date_Looker_Test"
}

