
#
# This LookML file was generated by AtScale on 2024-01-19T17:37:14.565169Z
#
# AtScale engine version: 2023.3.0.12549
# AtScale DesignCenter version: 2023.3.0.21052
# AtScale version: 2023.3.0.6480
# Organization: default
# Project: Looker_Date_Test

connection: "atscale-lm"
label: "Looker_Date_Test"


include: "/views/Looker__Date__Test/Looker__Date__Test.view.lkml"


explore: Looker_Date_Test {
  label: "Looker_Date_Test"
}

