
#
# This LookML file was generated by AtScale on 2024-06-12T17:51:51.367609810Z
#
# AtScale engine version: 2024.1.0.12792
# AtScale DesignCenter version: 2024.1.0.21169
# AtScale version: 2024.1.0.6834
# Organization: default
# Project: Looker_Date_Test

connection: "atscale-lm"
label: "Looker_Date_Test"


include: "/views/Looker__Date__Test/Looker__Date__Test.view.lkml"


explore: Looker_Date_Test {
  label: "Looker_Date_Test"
}

