
#
# This LookML file was generated by AtScale on 2023-04-25T15:38:22.794025Z
#
# AtScale engine version: 2023.1.0.12023
# AtScale DesignCenter version: 2023.1.0.20651
# AtScale version: 2023.1.0.5837
# Organization: default
# Project: Sales_Insights_lm

connection: "atscale-lm"
label: "Sales_Insights_lm"


include: "/views/Sales__Insights__lm/Internet__Sales__Cube__Lm.view.lkml"


explore: Internet_Sales_Cube_Lm {
  label: "Internet_Sales_Cube_Lm"
}

