
#
# This LookML file was generated by AtScale on 2024-03-22T10:34:47.524382484Z
#
# AtScale engine version: 2023.4.1.12728
# AtScale DesignCenter version: 2023.4.1.21138
# AtScale version: 2023.4.1.6713
# Organization: default
# Project: Sales Insights LM GBQ

connection: "atscale-lm"
label: "Sales Insights LM GBQ"


include: "/views/Sales_Insights_LM_GBQ/Internet_Sales_LM_GBQ.view.lkml"


explore: Internet_Sales_LM_GBQ {
  label: "Internet Sales LM GBQ"
}

