
#
# This LookML file was generated by AtScale on 2023-08-29T13:22:06.875327Z
#
# AtScale engine version: 2023.2.0.12240
# AtScale DesignCenter version: 2023.2.0.20954
# AtScale version: 2023.2.0.6157
# Organization: default
# Project: Sales_Insights_LM

connection: "atscale-lm"
label: "Sales_Insights_LM"


include: "/views/Sales__Insights__LM/Internet__Sales__Cube__Lm.view.lkml"


explore: Internet_Sales_Cube_Lm {
  label: "Internet_Sales_Cube_Lm"
}

