
#
# This LookML file was generated by AtScale on 2024-01-19T15:25:40.392178Z
#
# AtScale engine version: 2023.3.0.12549
# AtScale DesignCenter version: 2023.3.0.21052
# AtScale version: 2023.3.0.6480
# Organization: default
# Project: Sales_Insights_LM_GBQ

connection: "atscale-lm"
label: "Sales_Insights_LM_GBQ"


include: "/views/Sales__Insights__LM__GBQ/Internet__Sales__Cube__Lm.view.lkml"


explore: Internet_Sales_Cube_Lm {
  label: "Internet_Sales_Cube_Lm"
}

