
#
# This LookML file was generated by AtScale on 2023-04-25T15:32:35.418581Z
#
# AtScale engine version: 2023.1.0.12023
# AtScale DesignCenter version: 2023.1.0.20651
# AtScale version: 2023.1.0.5837
# Organization: default
# Project: Sales Insights

connection: "atscale-lm"
label: "Sales Insights"


include: "/views/Sales_Insights/Internet_Sales_Cube_Lm.view.lkml"


explore: Internet_Sales_Cube_Lm {
  label: "Internet Sales Cube Lm"
}

